# Generated by Django 6.0.5 on 2026-06-01 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('consumer', 'Consumer'), ('admin', 'Admin')], default='farmer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('language', models.CharField(choices=[('en', 'English'), ('dag', 'Dagbani')], default='en', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghana_card_number', models.CharField(blank=True, max_length=50)),
                ('ghana_card_photo', models.ImageField(blank=True, null=True, upload_to='kyc/ghana_cards/')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('gps_address', models.CharField(blank=True, max_length=100)),
                ('years_of_farming', models.PositiveSmallIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('credit_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('credit_score_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farmer_profiles',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('investor_type', models.CharField(choices=[('bank', 'Bank / MFI'), ('off_taker', 'Off-taker'), ('restaurant', 'Restaurant'), ('aggregator', 'Aggregator'), ('ngo', 'NGO / Development Partner')], max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('mandate_document', models.FileField(blank=True, null=True, upload_to='kyc/investor_mandates/')),
                ('max_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preferred_credit_types', models.JSONField(default=list)),
                ('preferred_regions', models.JSONField(default=list)),
                ('is_kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investor_profiles',
            },
        ),
    ]
