# Generated by Django 6.0.5 on 2026-06-01 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('credit_type', models.CharField(choices=[('funding', 'Funding'), ('inputs', 'Farm Inputs'), ('training', 'Training Enrolment')], max_length=20)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('repayment_period_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('input_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('scored', 'Scored'), ('matched', 'Matched to Investor'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('credit_score_at_submission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_applications', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('credit_type', models.CharField(choices=[('funding', 'Funding'), ('inputs', 'Farm Inputs'), ('training', 'Training Enrolment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_period_months', models.PositiveSmallIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pending_signature', 'Pending Signature'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='pending_signature', max_length=25)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('farmer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('investor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_agreements', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_agreements', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='credit.creditapplication')),
            ],
            options={
                'db_table': 'credit_agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('ghana_card', 'Ghana Card'), ('farm_cert', 'Farm Certificate'), ('farm_photo', 'Farm Photo'), ('season_record', 'Season Record'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='credit/documents/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credit.creditapplication')),
            ],
            options={
                'db_table': 'application_documents',
            },
        ),
    ]
