# Generated by Django 6.0.5 on 2026-06-01 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('flock_type', models.CharField(choices=[('broilers', 'Broilers'), ('layers', 'Layers'), ('mixed', 'Mixed')], max_length=20)),
                ('flock_size', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('gps_address', models.CharField(blank=True, max_length=100)),
                ('farm_size_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_water_source', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('registration_cert', models.FileField(blank=True, null=True, upload_to='farms/certs/')),
                ('farm_photo', models.ImageField(blank=True, null=True, upload_to='farms/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmAuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('outcome', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('concerns', 'Concerns Noted'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('flock_verified', models.PositiveIntegerField()),
                ('infrastructure_score', models.PositiveSmallIntegerField(help_text='Score out of 10')),
                ('management_score', models.PositiveSmallIntegerField(help_text='Score out of 10')),
                ('biosecurity_score', models.PositiveSmallIntegerField(help_text='Score out of 10')),
                ('report_document', models.FileField(blank=True, null=True, upload_to='audits/')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_reports', to='farms.farm')),
            ],
            options={
                'db_table': 'farm_audit_reports',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('flock_count', models.PositiveIntegerField()),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('feed_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('eggs_collected', models.PositiveIntegerField(default=0)),
                ('medication_given', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='farms.farm')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_activity_logs',
                'ordering': ['-date'],
                'unique_together': {('farm', 'date')},
            },
        ),
    ]
